DELETE FROM diylc_knowledge_base WHERE category IN (
  'guitar_pedals', 'guitars', 'guitar_amplifiers', 
  'hifi_amplifier', 'tube_circuits', 'ham_radio', 'synth_effects'
);

INSERT INTO diylc_knowledge_base (category, section, content) VALUES
('guitar_pedals', 'Popular Op-Amps for Guitar Pedals', 'TL072, JRC4558, and NE5532 are the most used op-amps for overdrive and distortion pedals. The JRC4558 is famous for its use in the Tube Screamer.'),
('guitar_pedals', 'Classic Transistors for Fuzz Effects', 'BC108, 2N2222, and 2N3904 are common choices for fuzz pedals. The BC108 gives a vintage fuzz tone, especially in classic Fuzz Face designs.'),
('guitar_pedals', 'Silicon vs Germanium Diodes for Clipping', '1N4148 silicon diodes produce sharper clipping, while 1N34A germanium diodes create softer, warmer distortion.'),
('guitar_pedals', 'Capacitor Choices for Tone Circuits', 'Film capacitors like WIMA or Panasonic are used for tone-shaping; electrolytics are used for coupling and power filtering.'),
('guitar_pedals', 'Common Footswitches for Pedal Bypass', '3PDT mechanical footswitches are standard for true-bypass switching in DIY guitar pedals.'),
('guitar_pedals', 'Power Supply Filtering in Pedals', '100uF electrolytic capacitors are often placed across DC inputs to reduce hum and stabilize supply voltage.'),
('guitar_pedals', 'Input Buffer Design', 'Op-amp buffers (like using half a TL072) or JFET buffers (like the J201) improve signal integrity and prevent tone loss.');

INSERT INTO diylc_knowledge_base (category, section, content) VALUES
('guitar_pedals', 'Boutique Op-Amps for Overdrive', 'RC4558P is the original op-amp used in the Ibanez Tube Screamer. Burr-Brown OPA2134 can be used for hi-fi pedal designs.'),
('guitar_pedals', 'Specialty Diodes for Clipping', 'BAT41 Schottky diodes are used for smooth, soft clipping in some boutique overdrive pedals. Red LEDs are sometimes used for harder, louder clipping.'),
('guitar_pedals', 'Germanium Transistors for Fuzz', 'AC128 and AC127 germanium transistors are prized for vintage fuzz pedals like the Fuzz Face. They provide a softer, more musical distortion.'),
('guitar_pedals', 'Voltage Regulators for Pedal Power', '78L05 and 78L09 are popular linear regulators used to stabilize pedal supply voltages.'),
('guitar_pedals', 'Classic Clipping Schemes', 'Symmetrical diode clipping produces Tube Screamer-like tones, while asymmetrical clipping produces a more amp-like breakup.');

INSERT INTO diylc_knowledge_base (category, section, content) VALUES
('guitar_pedals', 'Gain-Based Effects Overview', 'Boost pedals simply increase the signal level without adding clipping. Overdrive circuits use soft clipping to mimic a cranked tube amp, producing mild-to-moderate distortion that responds dynamically to playing. Distortion pedals use hard clipping to create a more aggressive, saturated tone. Fuzz pedals push clipping to extremes, often creating a thick, square-wave-like sound. Classic fuzzes used germanium transistors for a warmer feel, while silicon fuzzes are more aggressive and temperature-stable.'),
('guitar_pedals', 'Modulation Effects Overview', 'Modulation effects include chorus, flanger, phaser, and tremolo. A chorus pedal splits the signal, detunes one part, and recombines it for a rich ensemble sound. A flanger uses a short delay and feedback to create a sweeping, jet-like sound. A phaser passes the signal through all-pass filters to create moving notches, producing a swirling effect. Tremolo varies the signal volume up and down using an LFO, resulting in a pulsing sound.'),
('guitar_pedals', 'Delay and Reverb Effects', 'Delay pedals record the input and replay it after a set time, creating echo repeats. Analog delays use bucket-brigade chips for warm, degraded repeats, while digital delays offer clear, long echoes. Reverb pedals simulate acoustic spaces. Spring reverb uses actual springs to create reflections, while digital reverb models rooms, halls, and plates. Controls typically include delay time, feedback, mix level, and reverb decay.'),
('guitar_pedals', 'True Bypass vs Buffered Bypass', 'True bypass connects the input directly to the output when off, preserving tone but risking signal loss over long cable runs. Buffered bypass includes an active circuit that maintains signal strength and brightness. A good pedalboard mixes both types: buffered pedals early in the chain and true bypass for gain-based effects. Improper buffers can interfere with vintage fuzz and wah pedals.'),
('guitar_pedals', 'Power Supply and Headroom', 'Most analog pedals run on 9V DC. Higher voltage operation (12V or 18V) increases headroom, offering cleaner dynamics before distortion. Some designs use charge pumps to internally double voltage. Always check component voltage ratings before running pedals at higher voltages. Some fuzz pedals intentionally use low voltages (starving) to create gated, sputtery textures.'),
('guitar_pedals', 'Understanding Impedance', 'Pedal input impedance should be high (~1MΩ) to avoid tone loss from guitar pickups. Output impedance should be low to drive subsequent pedals or amplifiers. Buffers or emitter-follower stages help maintain low output impedance. AC coupling capacitors block DC between stages and shape the frequency response with resistors, acting as high-pass or low-pass filters.'),
('guitar_pedals', 'Choosing Diodes for Clipping', 'Diodes control clipping in distortion pedals. Germanium diodes clip around 0.3V for soft distortion. Silicon diodes clip around 0.7V for harder distortion. LEDs clip at 1.5–2V, allowing louder, more open sounds. Clipping can be symmetrical (even clipping) or asymmetrical (tube-like dynamics). Different diode arrangements drastically change a pedal’s tone and response.'),
('guitar_pedals', 'Choosing Op-Amps for Pedals', 'Op-amps provide amplification and shaping in pedals. Common choices include TL072, NE5532, and LM358. Different op-amps affect pedal noise levels, output drive, and tonal character. Swapping op-amps can subtly or dramatically alter a pedal’s feel. Some pedals use op-amps in feedback clipping designs, where diodes inside the feedback loop soften distortion.'),
('guitar_pedals', 'Transistors in Pedals', 'Transistors act as gain stages, buffers, or clipping elements. Germanium BJTs (e.g., AC128) offer warm, smooth distortion, but are temperature-sensitive. Silicon BJTs (e.g., 2N3904) offer brighter, more consistent performance. JFETs mimic tube-like saturation and are used in amp-in-a-box circuits. MOSFETs can clip signals softly and act as rugged buffers.'),
('guitar_pedals', 'Debugging: Power and Ground Checks', 'First, verify power and ground connections. Measure voltage across the pedal’s power input; 9V is typical. Check all grounds are tied together: input jack ground, output jack ground, and circuit ground. Reverse polarity can damage parts. Missing grounds are a very common cause of non-functional builds.'),
('guitar_pedals', 'Debugging: Component Orientation', 'Check that all polarized components are oriented correctly. Electrolytic capacitors have a positive lead. Diodes have a stripe marking the cathode. Transistors must match their pinout (C-B-E) to the circuit. Reversed components are one of the most common building mistakes and can kill a pedal instantly.'),
('guitar_pedals', 'Debugging: Finding Bad Solder Joints', 'Carefully inspect all solder joints. Cold solder joints appear dull or cracked and can cause intermittent issues. Reflow suspicious joints with fresh solder. Check for accidental solder bridges shorting pins together. Ensure all jack and switch wires are secure and in the right places. Many issues stem from simple bad soldering.'),
('guitar_pedals', 'Debugging: Signal Tracing with an Audio Probe', 'Use an audio probe to trace the guitar signal through the circuit. Build a probe with a 0.1uF capacitor connected to an amplifier input. Feed a test signal (guitar or oscillator) into the pedal and listen at key circuit points: input, after gain stages, after tone stack, before output. Identify where the signal disappears or changes.'),
('guitar_pedals', 'Grounding and Noise Problems', 'Poor grounding can cause hum, hiss, or high-pitched oscillations. Star grounding all grounds to a single point minimizes ground loops. Keep input and output wires short and separated to avoid feedback. Shielded cable can help reduce hum, especially for input wires in high-gain pedals.'),
('guitar_pedals', 'Modding: Clipping Diodes', 'Swapping clipping diodes changes the sound. Silicon diodes produce standard distortion. Germanium diodes produce smoother, vintage fuzz tones. LEDs clip less, making pedals louder and more open. Add switches to toggle between diode types for flexible clipping options.'),
('guitar_pedals', 'Modding: Tone Stack Changes', 'Changing capacitor or resistor values in a tone stack can shift the EQ response. Increasing tone cap values boosts bass. Reducing cap values tightens bass and boosts highs. Mid-scooped pedals like the Big Muff can be modded for flatter midrange or more aggressive tone by tweaking the tone circuit.'),
('guitar_pedals', 'Modding: Voltage Sag Controls', 'Adding a voltage sag control to a fuzz pedal simulates a dying battery. Use a pot to reduce supply voltage. Lower voltage makes fuzz sputtery, gated, and glitchy. Higher voltage keeps fuzz smooth and sustaining.'),
('guitar_pedals', 'Power Filtering Best Practices', 'Place a 47–100uF electrolytic capacitor across the power input to ground for ripple reduction. Add a 0.1uF ceramic capacitor to suppress high-frequency noise. Adding a reverse polarity protection diode can save the circuit if power is plugged in backward.'),
('guitar_pedals', 'Enclosure and Shielding', 'Use a metal enclosure for shielding against noise. Ensure jacks make solid ground contact to the box. Scrape paint around jack holes if needed for good ground contact. Keep inside wiring neat and short to avoid oscillations. Isolate jacks if ground loops become an issue.');

INSERT INTO diylc_knowledge_base (category, section, content) VALUES
('guitars', 'Common Potentiometers for Volume and Tone', 'CTS and Bourns make high-quality potentiometers. 250kΩ pots are used for single coils, 500kΩ for humbuckers.'),
('guitars', 'Switches for Pickup Selection', 'CRL 3-way and 5-way switches are standard for Strat and Tele-style guitars.'),
('guitars', 'Capacitors for Guitar Tone Controls', 'Typical tone capacitors are 0.022uF for humbuckers and 0.047uF for single-coil pickups.'),
('guitars', 'Shielding Materials for Noise Reduction', 'Copper tape and conductive paint are common materials used for shielding guitar cavities and pickguards.'),
('guitars', 'Common Pickup Wire Gauges', 'Vintage-style pickups use 42 AWG enameled copper wire, providing classic sound characteristics.');

INSERT INTO diylc_knowledge_base (category, section, content) VALUES
('guitars', 'Shielded Wiring for Guitars', 'Shielded twisted pair cables are often used in high-end guitars to reduce hum and noise.'),
('guitars', 'High-End Pickup Selector Switches', 'Switchcraft brand switches are known for their reliability in guitar wiring.'),
('guitars', 'Treble Bleed Mod', 'Adding a small capacitor (typically 150pF to 1nF) across the volume pot prevents treble loss when rolling back volume.');

INSERT INTO diylc_knowledge_base (category, section, content) VALUES
('guitar_amplifiers', 'Preamp Tubes for Guitar Amps', '12AX7 is the most widely used preamp tube for guitar amps, providing high gain. Alternatives like 12AT7 and 12AU7 offer lower gain options.'),
('guitar_amplifiers', 'Popular Power Tubes', '6L6GC, EL34, and EL84 tubes define the output stages of Fender, Marshall, and Vox amplifiers respectively.'),
('guitar_amplifiers', 'Solid-State Power Transistors', '2N3055 and MJ2955 transistors were common in early solid-state guitar amplifier designs.'),
('guitar_amplifiers', 'Output Transformers for Tube Amps', 'Hammond and ClassicTone are top brands for guitar amp output transformers. Choosing the correct impedance matching is critical.'),
('guitar_amplifiers', 'Rectifiers in Guitar Amps', 'Solid-state diodes like 1N5408 or tube rectifiers like 5AR4 are commonly used for converting AC to DC.');

INSERT INTO diylc_knowledge_base (category, section, content) VALUES
('guitar_amplifiers', 'How Tube Amplifiers Work', 'Tube guitar amplifiers boost the tiny signal from your guitar through several gain stages. A tube\'s heated cathode emits electrons, which are controlled by the grid and attracted to the plate (anode). This flow amplifies the signal. The signal path typically includes a preamp stage using 12AX7 tubes, a tone stack for EQ shaping, a phase inverter to split signals, and a power amp section with tubes like 6L6 or EL34 driving the output transformer and speaker. Coupling capacitors between stages block DC and allow the AC audio signal through, shaping the final tone. Distortion can occur at the preamp, power amp, or both, giving amps their dynamic, touch-sensitive feel.'),
('guitar_amplifiers', 'Classic Amplifier Topologies', 'Fender amps emphasize clean tones with 6L6/6V6 tubes and strong negative feedback, creating scooped mids and sparkling highs. Marshall amps modified Fender circuits with EL34 tubes and different tone stacks, giving a midrange-forward, aggressive crunch. Vox amps like the AC30 use EL84 tubes, cathode bias, and minimal negative feedback, producing bright, chimey tones with rich harmonics. Modern high-gain amps like Mesa Boogie add extra gain stages for heavy distortion and channel switching. Understanding these topologies helps predict how changes affect tone, feel, and distortion characteristics.'),
('guitar_amplifiers', 'Understanding Tube Types', '12AX7 tubes dominate preamp stages, offering high gain and rich harmonics. Lower gain tubes like 12AT7 or 12AY7 are used for cleaner sounds or phase inverter roles. Power tubes like 6V6 deliver soft breakup and sweetness at low volumes, while 6L6 tubes provide punchy clean headroom. EL84s are known for chimey, early breakup tones, while EL34s deliver aggressive British crunch. Rectifier tubes like 5Y3 and GZ34 convert AC to DC and introduce sag, compressing the tone under load. Choosing the right tube set is critical to shaping an amplifier’s sound and dynamic response.'),
('guitar_amplifiers', 'Power Supply Basics', 'The power transformer converts AC mains into high-voltage AC, which the rectifier (tube or diodes) converts to DC. Filter capacitors smooth this DC, and resistors or chokes further filter it before distribution. A tube rectifier introduces sag, giving a compressed, vintage feel, while solid-state diodes provide firm, immediate response. The output transformer matches the high-voltage, low-current signal of the tubes to the low-impedance speaker load, influencing tone and saturation. Transformer size and quality greatly impact bass response, volume, and clean headroom. A good power supply design ensures stable operation and defines the amplifier\'s feel under dynamic playing.'),
('guitar_amplifiers', 'Preamp Gain Stages', 'The preamp uses common-cathode triode stages to amplify the guitar signal. Each stage provides voltage gain, and cascading stages create overdrive. Coupling capacitors set bass response by forming high-pass filters with grid resistors. Early volume or gain controls set how hard later stages are driven, influencing where distortion occurs. Some designs add bright caps to retain treble at low volumes. Cathode followers, often used before tone stacks, buffer the signal and prevent tone loss. Designers tune component values to balance clean headroom, distortion onset, and frequency shaping, crafting the amp\'s voice and responsiveness.'),
('guitar_amplifiers', 'Tone Stack Overview', 'Most amps use a passive three-knob tone stack controlling bass, midrange, and treble. The classic Fender/Marshall tone stack scoops mids and emphasizes bass and treble. Adjusting cap and resistor values shifts the EQ focus: Marshall stacks have more mids, while Fender stacks are brighter and cleaner. Vox amps add a "Cut" control after the phase inverter for high-end roll-off. Some designs use Baxandall tone stacks, offering flatter response and independent bass/treble boost and cut. Tone stack placement in the circuit affects whether it shapes a clean or already-distorted signal, impacting final tone control.'),
('guitar_amplifiers', 'Phase Inverter Types', 'The phase inverter splits the signal into two out-of-phase signals for push-pull output stages. Cathodyne (split-load) inverters use a single triode and produce symmetrical outputs with minimal gain, found in small amps like the Fender Princeton. Long-Tailed Pair (LTP) inverters, common in larger amps, use two triodes to amplify and balance signals, providing more drive and symmetrical clipping. Paraphase inverters are older, less balanced designs. LTP inverters provide more headroom and are preferred in high-wattage amps, while cathodyne inverters contribute to smoother overdrive onset and vintage feel.'),
('guitar_amplifiers', 'Single-Ended vs Push-Pull Output', 'Single-ended output stages use one tube to amplify the full signal waveform, producing rich even-order harmonics and natural compression, but are low-power (5–15W). Push-pull stages use two tubes, each handling half the waveform, cancelling even harmonics and providing higher efficiency and cleaner output at low levels. Most high-power amps use push-pull configurations for 15–100W output. Push-pull amps can deliver tight bass and aggressive crunch when overdriven, while single-ended amps tend to have smoother saturation and a more forgiving, compressed feel at breakup.'),
('guitar_amplifiers', 'Class A vs Class AB Operation', 'Class A output stages conduct the entire signal cycle, producing smooth, immediate response but running hot and wasting power. Class AB stages conduct more than half the cycle, improving efficiency and output power. Most guitar amps are Class AB for practical reasons. Biasing impacts tone: cathode-biased amps self-bias with resistors, introducing some compression under load. Fixed-bias amps use negative voltage supplies, offering more clean headroom and tighter bass but requiring careful setup. Bias settings affect tube life, headroom, and distortion onset, and adjusting them can tune an amp\'s feel.'),
('guitar_amplifiers', 'Negative Feedback and Presence Control', 'Negative feedback loops feed a small portion of the output signal back into the phase inverter or earlier stage to reduce distortion and flatten frequency response. Fender amps use strong feedback for clean tones, while Vox amps often omit feedback for livelier response. Reducing feedback increases gain, touch sensitivity, and harmonic content but can also introduce noise. Presence controls adjust high-frequency feedback, boosting upper mids and treble by reducing feedback at those frequencies. Carefully tuning feedback levels shapes an amp\'s tightness, punch, and "feel" under dynamic playing conditions.'),
('guitar_amplifiers', 'Hybrid Amplifiers Explained', 'Hybrid amplifiers combine tubes and solid-state technology. Some use tube preamps and solid-state power amps (e.g., Marshall Valvestate), delivering tube warmth with reliable, lightweight solid-state amplification. Others, like vintage Music Man amps, use solid-state preamps feeding tube power amps, offering clean headroom with tube warmth at high volumes. Hybrids are cost-effective and durable but may sacrifice some "all-tube" dynamics, especially if the solid-state stage clips. Modern hybrids often run tubes at lower voltages ("starved plate") to simulate tube saturation safely. Well-designed hybrids blend tube tone generation with efficient solid-state output stages.'),
('guitar_amplifiers', 'Common Amplifier Troubleshooting', 'If an amp hums, squeals, or loses power, first suspect the tubes. Swapping known-good tubes one at a time can quickly isolate issues. Persistent hum could indicate failed filter capacitors or bad grounding. High-pitched squeals often result from bad lead dress or reversed feedback leads. Use an audio probe or signal injector to trace faults through the amp. Always power up new builds through a current-limiting light bulb tester to catch shorts safely. Pay attention to grounding layout and wire routing to minimize noise. Safety first: always discharge filter caps before working inside.'),
('guitar_amplifiers', 'Popular Modifications', 'Common amp mods include adjusting negative feedback levels to alter tightness and touch sensitivity, swapping coupling or bypass capacitors to change frequency response, and adding master volume controls for low-volume overdrive. Bright cap mods on volume pots can tame excessive treble or add sparkle. Power scaling or triode/pentode switches reduce output power for quieter playing. Adding bias adjustment pots helps tune tube performance. Modifications should be reversible where possible and done incrementally to evaluate tonal changes. Always follow safety practices when modifying high-voltage circuits.'),
('guitar_amplifiers', 'Safety and Layout Best Practices', 'Tube amps contain lethal voltages even when powered off. Always unplug the amp and discharge filter capacitors safely before working inside. Use star grounding or bus grounding to minimize hum. Twist heater wires tightly and route them away from sensitive preamp leads. Shield input signal wires and keep them short. Orient transformers at 90 degrees to each other to reduce magnetic coupling. Use fuses properly rated for safety. Following proper wiring and grounding techniques minimizes noise, oscillation, and risk of electric shock, ensuring a quiet, reliable, and safe amplifier build.');

INSERT INTO diylc_knowledge_base (category, section, content) VALUES
('guitar_amplifiers', 'Alternative Preamp Tubes', '5751 tubes can replace 12AX7s to lower gain slightly, offering more headroom.'),
('guitar_amplifiers', 'Popular Tube Rectifiers', '5U4GB rectifier tubes are used for more vintage sag compared to 5AR4/GZ34.'),
('guitar_amplifiers', 'Mercury Magnetics Transformers', 'Mercury Magnetics makes premium upgrade transformers for boutique guitar amplifiers.');

INSERT INTO diylc_knowledge_base (category, section, content) VALUES
('hifi_amplifier', 'Low-Noise Op-Amps for Hi-Fi', 'OPA2134, NE5532, and LM4562 are popular choices for ultra-low noise, high fidelity audio paths.'),
('hifi_amplifier', 'Preferred Capacitors for Audio', 'WIMA film capacitors and Nichicon Muse electrolytics are commonly used for signal coupling and power filtering in hi-fi amplifiers.'),
('hifi_amplifier', 'Power MOSFETs for Amplifier Output', 'IRFP240 and IRFP9240 are complementary pairs often used in Class AB hi-fi amplifier designs.'),
('hifi_amplifier', 'Toroidal Transformers for Power Supplies', 'Toroidal transformers are preferred in hi-fi amps for their low noise and efficiency. Brands like AnTek and Hammond are well regarded.');

INSERT INTO diylc_knowledge_base (category, section, content) VALUES
('hifi_amplifier', 'Ultra-Low Distortion Op-Amps', 'The ADA4898-2 and LME49720 op-amps are used in ultra-high-fidelity preamps and DACs.'),
('hifi_amplifier', 'Premium Capacitors for Audio', 'Mundorf and ClarityCap produce high-end film capacitors favored by audiophiles for signal paths.'),
('hifi_amplifier', 'Linear Power Supplies for Hi-Fi', 'Using linear regulated supplies reduces switching noise compared to SMPS in hi-fi amplifier designs.');

INSERT INTO diylc_knowledge_base (category, section, content) VALUES
('tube_circuits', 'Common Preamp Tubes', '12AX7 tubes are standard for gain stages, 12AU7 and 12AT7 for driver stages or reverb circuits.'),
('tube_circuits', 'Coupling Capacitors for Tube Amps', 'Orange Drop 716P series capacitors are famous for coupling stages in vintage and modern tube amps.'),
('tube_circuits', 'Rectifier Tubes Overview', '5Y3GT and GZ34 (5AR4) are popular rectifier tubes, providing different voltage sag characteristics.');

INSERT INTO diylc_knowledge_base (category, section, content) VALUES
('tube_circuits', '12DW7 Tubes', 'The 12DW7 is a hybrid tube with one half like a 12AX7 and one half like a 12AU7, useful in some amplifier circuits.'),
('tube_circuits', 'High Voltage Capacitors', 'Sprague Atom electrolytics are a premium choice for filter capacitors in tube amplifier power supplies.'),
('tube_circuits', 'Grid Stoppers and Protection', 'Using 1kΩ to 10kΩ grid stopper resistors can help prevent oscillations and radio interference in high-gain tube circuits.');

INSERT INTO diylc_knowledge_base (category, section, content) VALUES
('ham_radio', 'RF Transistors for Ham Projects', '2N2222 and 2N3866 transistors are used in VHF amplifiers and RF driver stages.'),
('ham_radio', 'Crystals for Oscillators', 'Common crystals like 7.040 MHz (40m band) and 14.318 MHz are used for building ham radio oscillators.'),
('ham_radio', 'Popular Tubes for Ham Transmitters', '6146B and 807 tubes are classic choices for homebrew transmitters.');

INSERT INTO diylc_knowledge_base (category, section, content) VALUES
('ham_radio', 'IF Transformers for Homebrew Receivers', '455 kHz IF transformers are widely used in AM radio circuits and simple ham receivers.'),
('ham_radio', 'Common Crystal Oscillator Frequencies', '10.000 MHz and 7.030 MHz are common crystals used for QRP CW transmitters.'),
('ham_radio', 'VFO Components', 'Varactor diodes like MV209 are often used in variable frequency oscillator circuits for fine-tuning.');